// Code generated by mockery. DO NOT EDIT.

package same_name_arg_and_type

import mock "github.com/stretchr/testify/mock"

// interfaceAMock is an autogenerated mock type for the interfaceA type
type interfaceAMock struct {
	mock.Mock
}

type interfaceAMock_Expecter struct {
	mock *mock.Mock
}

func (_m *interfaceAMock) EXPECT() *interfaceAMock_Expecter {
	return &interfaceAMock_Expecter{mock: &_m.Mock}
}

// DoB provides a mock function with given fields: interfaceB0
func (_m *interfaceAMock) DoB(interfaceB0 interfaceB) interfaceB {
	ret := _m.Called(interfaceB0)

	if len(ret) == 0 {
		panic("Missing Return() function for DoB")
	}

	var r0 interfaceB
	if rf, ok := ret.Get(0).(func(interfaceB) interfaceB); ok {
		r0 = rf(interfaceB0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaceB)
		}
	}

	return r0
}

// interfaceAMock_DoB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoB'
type interfaceAMock_DoB_Call struct {
	*mock.Call
}

// DoB is a helper method to define mock.On call
//   - interfaceB0 interfaceB
func (_e *interfaceAMock_Expecter) DoB(interfaceB0 interface{}) *interfaceAMock_DoB_Call {
	return &interfaceAMock_DoB_Call{Call: _e.mock.On("DoB", interfaceB0)}
}

func (_c *interfaceAMock_DoB_Call) Run(run func(interfaceB0 interfaceB)) *interfaceAMock_DoB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaceB))
	})
	return _c
}

func (_c *interfaceAMock_DoB_Call) Return(_a0 interfaceB) *interfaceAMock_DoB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *interfaceAMock_DoB_Call) RunAndReturn(run func(interfaceB) interfaceB) *interfaceAMock_DoB_Call {
	_c.Call.Return(run)
	return _c
}

// DoB0 provides a mock function with given fields: interfaceB
func (_m *interfaceAMock) DoB0(interfaceB interfaceB0) interfaceB0 {
	ret := _m.Called(interfaceB)

	if len(ret) == 0 {
		panic("Missing Return() function for DoB0")
	}

	var r0 interfaceB0
	if rf, ok := ret.Get(0).(func(interfaceB0) interfaceB0); ok {
		r0 = rf(interfaceB)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaceB0)
		}
	}

	return r0
}

// interfaceAMock_DoB0_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoB0'
type interfaceAMock_DoB0_Call struct {
	*mock.Call
}

// DoB0 is a helper method to define mock.On call
//   - interfaceB interfaceB0
func (_e *interfaceAMock_Expecter) DoB0(interfaceB interface{}) *interfaceAMock_DoB0_Call {
	return &interfaceAMock_DoB0_Call{Call: _e.mock.On("DoB0", interfaceB)}
}

func (_c *interfaceAMock_DoB0_Call) Run(run func(interfaceB interfaceB0)) *interfaceAMock_DoB0_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaceB0))
	})
	return _c
}

func (_c *interfaceAMock_DoB0_Call) Return(_a0 interfaceB0) *interfaceAMock_DoB0_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *interfaceAMock_DoB0_Call) RunAndReturn(run func(interfaceB0) interfaceB0) *interfaceAMock_DoB0_Call {
	_c.Call.Return(run)
	return _c
}

// DoB0v2 provides a mock function with given fields: interfaceB00
func (_m *interfaceAMock) DoB0v2(interfaceB00 interfaceB0) interfaceB0 {
	ret := _m.Called(interfaceB00)

	if len(ret) == 0 {
		panic("Missing Return() function for DoB0v2")
	}

	var r0 interfaceB0
	if rf, ok := ret.Get(0).(func(interfaceB0) interfaceB0); ok {
		r0 = rf(interfaceB00)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaceB0)
		}
	}

	return r0
}

// interfaceAMock_DoB0v2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoB0v2'
type interfaceAMock_DoB0v2_Call struct {
	*mock.Call
}

// DoB0v2 is a helper method to define mock.On call
//   - interfaceB00 interfaceB0
func (_e *interfaceAMock_Expecter) DoB0v2(interfaceB00 interface{}) *interfaceAMock_DoB0v2_Call {
	return &interfaceAMock_DoB0v2_Call{Call: _e.mock.On("DoB0v2", interfaceB00)}
}

func (_c *interfaceAMock_DoB0v2_Call) Run(run func(interfaceB00 interfaceB0)) *interfaceAMock_DoB0v2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaceB0))
	})
	return _c
}

func (_c *interfaceAMock_DoB0v2_Call) Return(_a0 interfaceB0) *interfaceAMock_DoB0v2_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *interfaceAMock_DoB0v2_Call) RunAndReturn(run func(interfaceB0) interfaceB0) *interfaceAMock_DoB0v2_Call {
	_c.Call.Return(run)
	return _c
}

// newInterfaceAMock creates a new instance of interfaceAMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInterfaceAMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *interfaceAMock {
	mock := &interfaceAMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
