// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	errors "github.com/pkg/errors"
	mock "github.com/stretchr/testify/mock"
)

// stackTracer is an autogenerated mock type for the stackTracer type
type stackTracer struct {
	mock.Mock
}

// StackTrace provides a mock function with given fields:
func (_m *stackTracer) StackTrace() errors.StackTrace {
	ret := _m.Called()

	var r0 errors.StackTrace
	if rf, ok := ret.Get(0).(func() errors.StackTrace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.StackTrace)
		}
	}

	return r0
}
