// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package mocks

import mock "github.com/stretchr/testify/mock"

type FuncArgsCollisionMock struct {
	mock.Mock
}

func (_m *FuncArgsCollisionMock) Foo(ret interface{}) error {
	args := _m.Called(ret)
	return args.Error(0)
}
