// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package mocks

import mock "github.com/stretchr/testify/mock"

type requester_unexportedMock struct {
	mock.Mock
}

func (_m *requester_unexportedMock) Get() {
	_m.Called()
}
