// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package mocks

import mock "github.com/stretchr/testify/mock"

type Requester4Mock struct {
	mock.Mock
}

func (_m *Requester4Mock) Get() {
	_m.Called()
}
