linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - contextcheck
    - durationcheck
    - copyloopvar
    - gocheckcompilerdirectives
    - gosec
    - loggercheck
    - nilerr
    - prealloc
    - predeclared
    - reassign
    - revive
    - testifylint
linters-settings:
  revive:
    enable-all-rules: false
    rules:
      - name: 'var-naming'
  staticcheck:
    checks:
    - all
    - '-SA1024'
  testifylint:
    disable-all: true
    enable:
      - compares
      - empty
      - expected-actual
      - len
  gosimple:
    checks:
      - S1000
      - S1001
      - S1003
      - S1004
      - S1005
      - S1006
      - S1007
      - S1008
      - S1009
      - S1010
      - S1011
      - S1012
      - S1016
      - S1017
      - S1018
      - S1019
      - S1020
      - S1021
      - S1023
      - S1024
      - S1025
      - S1028
      - S1029
      - S1030
      - S1031
      - S1032
      - S1033
      - S1034
      - S1035
      - S1036
      - S1037
      - S1038
      - S1039
      - S1040
issues:
  exclude-rules:
    - linters:
        - revive
      text: "var-naming: don't use an underscore in package name"
