linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - errcheck
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - durationcheck
    - copyloopvar
    - gocheckcompilerdirectives
    - gosec
    - loggercheck
    - nilerr
    - prealloc
    - predeclared
    - reassign
    - revive
    - testifylint
linters-settings:
  revive:
    enable-all-rules: false
    rules:
      - name: 'var-naming'
  staticcheck:
    checks:
    - all
    - '-SA1024'
  testifylint:
    disable-all: true
    enable:
      - compares
      - empty
      - expected-actual
      - len
issues:
  exclude-rules:
    - linters:
        - revive
      text: "var-naming: don't use an underscore in package name"
