---
project_name: mockery
before:
    hooks:
      - go mod download
builds:
  - main: ./cmd/mockery/mockery.go
    ldflags:
      - -s -w -X github.com/vektra/mockery/mockery.SemVer={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
checksum:
    name_template: "checksum.txt"
snapshot:
    name_template: "{{ .Tag }}-next"
changelog:
    sort: asc
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - mockery
    image_templates:
      - 'vektra/mockery:{{ .Tag }}'
      - 'vektra/mockery:v{{ .Major }}'
      - 'vektra/mockery:v{{ .Major }}.{{ .Minor }}'
      - 'vektra/mockery:latest'
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
brews:
  - homepage: https://github.com/vektra/mockery
    description: "A mock code autogenerator for Go"
    github:
        owner: vektra
        name: homebrew-tap
    folder: Formula
    test: |
        system "#{bin}mockery --version"
