template: "mockery"
tags: "custom2"
formatter: "goimports"
all: True
dir: "{{.InterfaceDirRelative}}"
mockname: "Mock{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "mocks_{{.SrcPackageName}}_test.go"
template-data:
  boilerplate-file: "./.boilerplate.txt"
packages:
  github.com/vektra/mockery/v3/internal/fixtures/buildtag/comment:
  github.com/vektra/mockery/v3/internal/fixtures/example_project/replace_type:
    config:
      recursive: True
    interfaces:
      RType:
        configs:
        - {}
        - mockname: RTypeReplaced1
          replace-type:
            github.com/vektra/mockery/v3/internal/fixtures/example_project/replace_type/rti/rt1:
              RType1:
                pkg-path: github.com/vektra/mockery/v3/internal/fixtures/example_project/replace_type/rti/rt2
                type-name: RType2

  github.com/vektra/mockery/v3/internal/fixtures:
    interfaces:
      RequesterVariadic:
        configs:
          - mockname: MockRequesterVariadicOneArgument
            template-data:
              unroll-variadic: False
          - mockname: MockRequesterVariadic
            template-data:
              unroll-variadic: True
      Expecter:
        configs:
          - mockname: MockExpecterAndRolledVariadic
            template-data:
              unroll-variadic: False
          - mockname: MockExpecter
            template-data:
              unroll-variadic: True
      VariadicNoReturnInterface:
        config:
          template-data:
            unroll-variadic: False
  github.com/vektra/mockery/v3/internal/fixtures/recursive_generation:
    config:
      recursive: True
  github.com/vektra/mockery/v3/internal/fixtures/empty_return:
  github.com/vektra/mockery/v3/internal/fixtures/method_args/same_name_arg_and_type:
  github.com/vektra/mockery/v3/internal/fixtures/iface_typed_param:
  github.com/vektra/mockery/v3/internal/fixtures/example_project:
  github.com/vektra/mockery/v3/internal/fixtures/index_list_expr:
  github.com/vektra/mockery/v3/internal/fixtures/iface_new_type:
  github.com/vektra/mockery/v3/internal/fixtures/type_alias:
  io:
    config:
      all: True
      dir: internal/fixtures/
      pkgname: test

