template: matryer
mockname: "Moq{{.InterfaceName}}"
filename: "mocks_matryer_{{.SrcPackageName}}_test.go"
all: true
template-data:
  skip-ensure: False
  stub-impl: True
  with-resets: True
  boilerplate-file: "./.boilerplate.txt"
packages:
  github.com/vektra/mockery/v3/internal/fixtures:
    config:
      all: false
      include-regex: '.*'
      exclude-regex: 'RequesterGenerics'
    interfaces:
      Requester:
        configs:
          - mockname: "Moq{{.InterfaceName}}SkipEnsure"
            template-data:
              skip-ensure: True
          - {}
          - mockname: StubMatyer{{.InterfaceName}}
            template-data:
              stub-impl: True
  github.com/vektra/mockery/v3/internal/fixtures/empty_return:
    interfaces:
      EmptyReturn:
        configs:
          - mockname: StubMatyer{{.InterfaceName}}
            template-data:
              stub-impl: True