quiet: False
disable-version-string: True
mockname: "{{.InterfaceName}}Moq"
filename: "{{.InterfaceName | snakecase }}_moq.go"
dir: "mocks/moq/{{.PackagePath}}"
style: moq
packages:
  github.com/vektra/mockery/v2/pkg/fixtures:
    config:
      include-regex: '.*'
      exclude-regex: 'RequesterGenerics|UnsafeInterface|requester_unexported'
      outpkg: test
      template-map:
        with-resets: true
        skip-ensure: false
        stub-impl: false
      inpackage: false
  github.com/vektra/mockery/v2/pkg/fixtures/inpackage:
    config:
      dir: "{{.InterfaceDir}}"
      all: True
      outpkg: "{{.PackageName}}"
      inpackage: true
