coverage:
  precision: 5
  round: down
  range: "0...100"
  status:
    patch:
      default:
        target: 0%
        threshold: 35%
        base: auto
    project:
      default:
        target: 0%
        threshold: 35%
        base: auto 
