// TEST MOCKERY BOILERPLATE

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dep

import (
	mock "github.com/stretchr/testify/mock"
	dep0 "github.com/vektra/mockery/v3/internal/fixtures/inpackage_import_collision/dep"
)

// NewMockIface creates a new instance of MockIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIface {
	mock := &MockIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIface is an autogenerated mock type for the Iface type
type MockIface struct {
	mock.Mock
}

type MockIface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIface) EXPECT() *MockIface_Expecter {
	return &MockIface_Expecter{mock: &_m.Mock}
}

// M provides a mock function for the type MockIface
func (_mock *MockIface) M() dep0.T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for M")
	}

	var r0 dep0.T
	if returnFunc, ok := ret.Get(0).(func() dep0.T); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(dep0.T)
	}
	return r0
}

// MockIface_M_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'M'
type MockIface_M_Call struct {
	*mock.Call
}

// M is a helper method to define mock.On call
func (_e *MockIface_Expecter) M() *MockIface_M_Call {
	return &MockIface_M_Call{Call: _e.mock.On("M")}
}

func (_c *MockIface_M_Call) Run(run func()) *MockIface_M_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIface_M_Call) Return(t dep0.T) *MockIface_M_Call {
	_c.Call.Return(t)
	return _c
}

func (_c *MockIface_M_Call) RunAndReturn(run func() dep0.T) *MockIface_M_Call {
	_c.Call.Return(run)
	return _c
}
