// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import (
	mock "github.com/stretchr/testify/mock"
	test "github.com/vektra/mockery/v2/pkg/fixtures"
)

type AMock struct {
	mock.Mock
}

func (_m *AMock) Call() (test.B, error) {
	args := _m.Called()
	return args.Get(0).(test.B), args.Error(1)
}
