// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import mock "github.com/stretchr/testify/mock"

type BlankMock struct {
	mock.Mock
}

func (_m *BlankMock) Create(x interface{}) error {
	args := _m.Called(x)
	return args.Error(0)
}
