// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import mock "github.com/stretchr/testify/mock"

type ConsulLockMock struct {
	mock.Mock
}

func (_m *ConsulLockMock) Lock(_a0 <-chan struct{}) (<-chan struct{}, error) {
	args := _m.Called(_a0)
	return args.Get(0).(<-chan struct{}), args.Error(1)
}
func (_m *ConsulLockMock) Unlock() error {
	args := _m.Called()
	return args.Error(0)
}
