// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import (
	mock "github.com/stretchr/testify/mock"
	fixtures "github.com/vektra/mockery/v2/pkg/fixtures"

	test "github.com/vektra/mockery/v2/pkg/fixtures/test"
)

type ImportsSameAsPackageMock struct {
	mock.Mock
}

func (_m *ImportsSameAsPackageMock) A() test.B {
	args := _m.Called()
	return args.Get(0).(test.B)
}
func (_m *ImportsSameAsPackageMock) B() fixtures.KeyManager {
	args := _m.Called()
	return args.Get(0).(fixtures.KeyManager)
}
func (_m *ImportsSameAsPackageMock) C(_a0 fixtures.C) {
	_m.Called(_a0)
}
