// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import mock "github.com/stretchr/testify/mock"

type MapFuncMock struct {
	mock.Mock
}

func (_m *MapFuncMock) Get(m map[string]func(string) string) error {
	args := _m.Called(m)
	return args.Error(0)
}
