// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import mock "github.com/stretchr/testify/mock"

type RequesterArgSameAsPkgMock struct {
	mock.Mock
}

func (_m *RequesterArgSameAsPkgMock) Get(_a0 string) {
	_m.Called(_a0)
}
