// TEST MOCKERY BOILERPLATE

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package iface_typed_param_lowercase

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGetterIfaceTypedParam creates a new instance of MockGetterIfaceTypedParam. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetterIfaceTypedParam[a comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetterIfaceTypedParam[a] {
	mock := &MockGetterIfaceTypedParam[a]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetterIfaceTypedParam is an autogenerated mock type for the GetterIfaceTypedParam type
type MockGetterIfaceTypedParam[a comparable] struct {
	mock.Mock
}

type MockGetterIfaceTypedParam_Expecter[a comparable] struct {
	mock *mock.Mock
}

func (_m *MockGetterIfaceTypedParam[a]) EXPECT() *MockGetterIfaceTypedParam_Expecter[a] {
	return &MockGetterIfaceTypedParam_Expecter[a]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGetterIfaceTypedParam
func (_mock *MockGetterIfaceTypedParam[a]) Get(v a) a {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 a
	if returnFunc, ok := ret.Get(0).(func(a) a); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(a)
		}
	}
	return r0
}

// MockGetterIfaceTypedParam_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetterIfaceTypedParam_Get_Call[a comparable] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - v a
func (_e *MockGetterIfaceTypedParam_Expecter[a]) Get(v any) *MockGetterIfaceTypedParam_Get_Call[a] {
	return &MockGetterIfaceTypedParam_Get_Call[a]{Call: _e.mock.On("Get", v)}
}

func (_c *MockGetterIfaceTypedParam_Get_Call[a]) Run(run func(v a)) *MockGetterIfaceTypedParam_Get_Call[a] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 a
		if args[0] != nil {
			arg0 = args[0].(a)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGetterIfaceTypedParam_Get_Call[a]) Return(v1 a) *MockGetterIfaceTypedParam_Get_Call[a] {
	_c.Call.Return(v1)
	return _c
}

func (_c *MockGetterIfaceTypedParam_Get_Call[a]) RunAndReturn(run func(v a) a) *MockGetterIfaceTypedParam_Get_Call[a] {
	_c.Call.Return(run)
	return _c
}
