// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"reflect"

	mock "github.com/stretchr/testify/mock"
)

// IfaceWithBuildTagInComment is an autogenerated mock type for the IfaceWithBuildTagInComment type
type IfaceWithBuildTagInComment struct {
	mock.Mock
}

// Sprintf provides a mock function with given fields: format, a
func (_m *IfaceWithBuildTagInComment) Sprintf(format string, a ...interface{}) string {
	var vararg []interface{}
	if len(a) > 0 {
		vararg = make([]interface{}, len(a))
		for _i, _a := range a {
			vararg[_i] = _a
		}
	}

	ret := _m.Called(format, vararg)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, ...interface{}) string); ok {
		r0 = rf(format, a...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIfaceWithBuildTagInComment interface {
	mock.TestingT
	Cleanup(func())
}

// NewIfaceWithBuildTagInComment creates a new instance of IfaceWithBuildTagInComment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIfaceWithBuildTagInComment(t mockConstructorTestingTNewIfaceWithBuildTagInComment) *IfaceWithBuildTagInComment {
	mock := &IfaceWithBuildTagInComment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

func (_m *IfaceWithBuildTagInComment) rollVariadic(methodName string, arguments ...interface{}) []interface{} {
	sig := _m.getMethodSignature(methodName)

	if !sig.IsVariadic() {
		return arguments
	}

	variadicIndex := sig.NumIn() - 1
	if len(arguments) == sig.NumIn() && arguments[variadicIndex] == mock.Anything {
		return arguments
	}

	newArgs := make([]interface{}, sig.NumIn())

	copy(newArgs, arguments[0:variadicIndex])

	if len(arguments) >= sig.NumIn() {
		newArgs[variadicIndex] = arguments[variadicIndex:]
	} else {
		newArgs[variadicIndex] = []interface{}(nil)
	}

	return newArgs
}

func (_m *IfaceWithBuildTagInComment) getMethodSignature(methodName string) reflect.Type {
	switch methodName {
	case "Sprintf":
		return reflect.TypeOf(_m.Sprintf)
	default:
		panic("Invalid method name")
	}
}

func (_m *IfaceWithBuildTagInComment) On(methodName string, arguments ...interface{}) *mock.Call {
	arguments = _m.rollVariadic(methodName, arguments...)
	return _m.Mock.On(methodName, arguments...)
}

func (_m *IfaceWithBuildTagInComment) AssertCalled(t mock.TestingT, methodName string, arguments ...interface{}) bool {
	arguments = _m.rollVariadic(methodName, arguments...)
	return _m.Mock.AssertCalled(t, methodName, arguments...)
}

func (_m *IfaceWithBuildTagInComment) AssertNotCalled(t mock.TestingT, methodName string, arguments ...interface{}) bool {
	arguments = _m.rollVariadic(methodName, arguments...)
	return _m.Mock.AssertNotCalled(t, methodName, arguments...)
}
