// Code generated by mockery. DO NOT EDIT.

package iface_new_type_test

import mock "github.com/stretchr/testify/mock"

// MockInterface2 is an autogenerated mock type for the Interface2 type
type MockInterface2 struct {
	mock.Mock
}

type MockInterface2_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface2) EXPECT() *MockInterface2_Expecter {
	return &MockInterface2_Expecter{mock: &_m.Mock}
}

// Method1 provides a mock function with no fields
func (_m *MockInterface2) Method1() {
	_m.Called()
}

// MockInterface2_Method1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method1'
type MockInterface2_Method1_Call struct {
	*mock.Call
}

// Method1 is a helper method to define mock.On call
func (_e *MockInterface2_Expecter) Method1() *MockInterface2_Method1_Call {
	return &MockInterface2_Method1_Call{Call: _e.mock.On("Method1")}
}

func (_c *MockInterface2_Method1_Call) Run(run func()) *MockInterface2_Method1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface2_Method1_Call) Return() *MockInterface2_Method1_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface2_Method1_Call) RunAndReturn(run func()) *MockInterface2_Method1_Call {
	_c.Run(run)
	return _c
}

// NewMockInterface2 creates a new instance of MockInterface2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface2(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface2 {
	mock := &MockInterface2{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
