// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	test "github.com/vektra/mockery/v2/pkg/fixtures"
)

// NewA creates a new instance of A. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewA(t interface {
	mock.TestingT
	Cleanup(func())
}) *A {
	mock := &A{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// A is an autogenerated mock type for the A type
type A struct {
	mock.Mock
}

// Call provides a mock function for the type A
func (_mock *A) Call() (test.B, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 test.B
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (test.B, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() test.B); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(test.B)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type A_expecter struct {
	mock *mock.Mock
}

func (_m *A) EXPECT() *A_expecter {
	return &A_expecter{mock: &_m.Mock}
}
