// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewGenericInterface creates a new instance of GenericInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenericInterface[MParam any](t interface {
	mock.TestingT
	Cleanup(func())
}) *GenericInterface[MParam] {
	mock := &GenericInterface[MParam]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GenericInterface is an autogenerated mock type for the GenericInterface type
type GenericInterface[MParam any] struct {
	mock.Mock
}

type GenericInterface_Expecter[MParam any] struct {
	mock *mock.Mock
}

func (_m *GenericInterface[MParam]) EXPECT() *GenericInterface_Expecter[MParam] {
	return &GenericInterface_Expecter[MParam]{mock: &_m.Mock}
}

// Func provides a mock function for the type GenericInterface
func (_mock *GenericInterface[MParam]) Func(argParam *M) int {
	ret := _mock.Called(argParam)

	if len(ret) == 0 {
		panic("no return value specified for Func")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(*M) int); ok {
		r0 = returnFunc(argParam)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// GenericInterface_Func_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Func'
type GenericInterface_Func_Call[MParam any] struct {
	*mock.Call
}

// Func is a helper method to define mock.On call
//   - argParam
func (_e *GenericInterface_Expecter[MParam]) Func(argParam interface{}) *GenericInterface_Func_Call[MParam] {
	return &GenericInterface_Func_Call[MParam]{Call: _e.mock.On("Func", argParam)}
}

func (_c *GenericInterface_Func_Call[MParam]) Run(run func(argParam *M)) *GenericInterface_Func_Call[MParam] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*M))
	})
	return _c
}

func (_c *GenericInterface_Func_Call[MParam]) Return(nOutParam int) *GenericInterface_Func_Call[MParam] {
	_c.Call.Return(nOutParam)
	return _c
}

func (_c *GenericInterface_Func_Call[MParam]) RunAndReturn(run func(argParam *M) int) *GenericInterface_Func_Call[MParam] {
	_c.Call.Return(run)
	return _c
}
