// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// NewRequesterArgSameAsNamedImport creates a new instance of RequesterArgSameAsNamedImport. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequesterArgSameAsNamedImport(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequesterArgSameAsNamedImport {
	mock := &RequesterArgSameAsNamedImport{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RequesterArgSameAsNamedImport is an autogenerated mock type for the RequesterArgSameAsNamedImport type
type RequesterArgSameAsNamedImport struct {
	mock.Mock
}

// Get provides a mock function for the type RequesterArgSameAsNamedImport
func (_mock *RequesterArgSameAsNamedImport) Get(jsonMoqParam string) *json.RawMessage {
	ret := _mock.Called(jsonMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *json.RawMessage
	if returnFunc, ok := ret.Get(0).(func(string) *json.RawMessage); ok {
		r0 = returnFunc(jsonMoqParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}
	return r0
}

type RequesterArgSameAsNamedImport_expecter struct {
	mock *mock.Mock
}

func (_m *RequesterArgSameAsNamedImport) EXPECT() *RequesterArgSameAsNamedImport_expecter {
	return &RequesterArgSameAsNamedImport_expecter{mock: &_m.Mock}
}
