// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// RequesterVariadicOmitEmpty is an autogenerated mock type for the RequesterVariadic type
type RequesterVariadicOmitEmpty struct {
	mock.Mock
}

// Get provides a mock function with given fields: values
func (_m *RequesterVariadicOmitEmpty) Get(values ...string) bool {
	var tmpRet mock.Arguments
	if len(values) > 0 {
		tmpRet = _m.Called(values)
	} else {
		tmpRet = _m.Called()
	}

	ret := tmpRet

	var r0 bool
	if rf, ok := ret.Get(0).(func(...string) bool); ok {
		r0 = rf(values...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MultiWriteToFile provides a mock function with given fields: filename, w
func (_m *RequesterVariadicOmitEmpty) MultiWriteToFile(filename string, w ...io.Writer) string {
	var tmpRet mock.Arguments
	if len(w) > 0 {
		tmpRet = _m.Called(filename, w)
	} else {
		tmpRet = _m.Called(filename)
	}

	ret := tmpRet

	var r0 string
	if rf, ok := ret.Get(0).(func(string, ...io.Writer) string); ok {
		r0 = rf(filename, w...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OneInterface provides a mock function with given fields: a
func (_m *RequesterVariadicOmitEmpty) OneInterface(a ...interface{}) bool {
	var tmpRet mock.Arguments
	if len(a) > 0 {
		tmpRet = _m.Called(a)
	} else {
		tmpRet = _m.Called()
	}

	ret := tmpRet

	var r0 bool
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(a...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Sprintf provides a mock function with given fields: format, a
func (_m *RequesterVariadicOmitEmpty) Sprintf(format string, a ...interface{}) string {
	var tmpRet mock.Arguments
	if len(a) > 0 {
		tmpRet = _m.Called(format, a)
	} else {
		tmpRet = _m.Called(format)
	}

	ret := tmpRet

	var r0 string
	if rf, ok := ret.Get(0).(func(string, ...interface{}) string); ok {
		r0 = rf(format, a...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewRequesterVariadicOmitEmpty interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequesterVariadicOmitEmpty creates a new instance of RequesterVariadicOmitEmpty. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequesterVariadicOmitEmpty(t mockConstructorTestingTNewRequesterVariadicOmitEmpty) *RequesterVariadicOmitEmpty {
	mock := &RequesterVariadicOmitEmpty{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
