// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VariadicNoReturnInterface is an autogenerated mock type for the VariadicNoReturnInterface type
type VariadicNoReturnInterface struct {
	mock.Mock
}

type VariadicNoReturnInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *VariadicNoReturnInterface) EXPECT() *VariadicNoReturnInterface_Expecter {
	return &VariadicNoReturnInterface_Expecter{mock: &_m.Mock}
}

// VariadicNoReturn provides a mock function with given fields: j, is
func (_m *VariadicNoReturnInterface) VariadicNoReturn(j int, is ...interface{}) {
	if len(is) > 0 {
		_m.Called(j, is)
	} else {
		_m.Called(j)
	}

}

// VariadicNoReturnInterface_VariadicNoReturn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VariadicNoReturn'
type VariadicNoReturnInterface_VariadicNoReturn_Call struct {
	*mock.Call
}

// VariadicNoReturn is a helper method to define mock.On call
//   - j int
//   - is ...interface{}
func (_e *VariadicNoReturnInterface_Expecter) VariadicNoReturn(j interface{}, is ...interface{}) *VariadicNoReturnInterface_VariadicNoReturn_Call {
	return &VariadicNoReturnInterface_VariadicNoReturn_Call{Call: _e.mock.On("VariadicNoReturn",
		append([]interface{}{j}, is...)...)}
}

func (_c *VariadicNoReturnInterface_VariadicNoReturn_Call) Run(run func(j int, is ...interface{})) *VariadicNoReturnInterface_VariadicNoReturn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(int), variadicArgs...)
	})
	return _c
}

func (_c *VariadicNoReturnInterface_VariadicNoReturn_Call) Return() *VariadicNoReturnInterface_VariadicNoReturn_Call {
	_c.Call.Return()
	return _c
}

// NewVariadicNoReturnInterface creates a new instance of VariadicNoReturnInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVariadicNoReturnInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VariadicNoReturnInterface {
	mock := &VariadicNoReturnInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
