// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GetInt is an autogenerated mock type for the GetInt type
type GetInt struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *GetInt) Get() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type NewGetIntT interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetInt creates a new instance of GetInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetInt(t NewGetIntT) *GetInt {
	mock := &GetInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
