// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Requester4 is an autogenerated mock type for the Requester4 type
type Requester4 struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Requester4) Get() {
	_m.Called()
}

// NewRequester4 creates a new instance of Requester4. It also registers a cleanup function to assert the mocks expectations.
func NewRequester4(t testing.TB) *Requester4 {
	mock := &Requester4{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
