// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sibling is an autogenerated mock type for the Sibling type
type Sibling struct {
	mock.Mock
}

// DoSomething provides a mock function with given fields:
func (_m *Sibling) DoSomething() {
	_m.Called()
}
