// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sibling is an autogenerated mock type for the Sibling type
type Sibling struct {
	mock.Mock
}

// DoSomething provides a mock function with given fields:
func (_m *Sibling) DoSomething() {
	_m.Called()
}

type NewSiblingT interface {
	mock.TestingT
	Cleanup(func())
}

// NewSibling creates a new instance of Sibling. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSibling(t NewSiblingT) *Sibling {
	mock := &Sibling{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
