// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: gomock
// source: io (interfaces: Reader, Writer, Closer, Seeker, ReadWriter, ReadCloser, WriteCloser, ReadWriteCloser, ReadSeeker, ReadSeekCloser, WriteSeeker, ReadWriteSeeker, ReaderFrom, WriterTo, ReaderAt, WriterAt, ByteReader, ByteScanner, ByteWriter, RuneReader, RuneScanner, StringWriter)
// TEST MOCKERY BOILERPLATE

// Package test is a generated GoMock package.
package test

import (
	"io"
	"reflect"

	"go.uber.org/mock/gomock"
)

// GoMockReader is a mock of Reader interface.
type GoMockReader struct {
	ctrl     *gomock.Controller
	recorder *GoMockReaderMockRecorder
	isgomock struct{}
}

// GoMockReaderMockRecorder is the mock recorder for GoMockReader.
type GoMockReaderMockRecorder struct {
	mock *GoMockReader
}

// NewGoMockReader creates a new mock instance.
func NewGoMockReader(ctrl *gomock.Controller) *GoMockReader {
	mock := &GoMockReader{ctrl: ctrl}
	mock.recorder = &GoMockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReader) EXPECT() *GoMockReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *GoMockReader) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReaderMockRecorder) Read(p any) *GoMockReaderReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReader)(nil).Read), p)
	return &GoMockReaderReadCall{Call: call}
}

// GoMockReaderReadCall wrap *gomock.Call
type GoMockReaderReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReaderReadCall) Return(n int, err error) *GoMockReaderReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReaderReadCall) Do(f func([]byte) (int, error)) *GoMockReaderReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReaderReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReaderReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockWriter is a mock of Writer interface.
type GoMockWriter struct {
	ctrl     *gomock.Controller
	recorder *GoMockWriterMockRecorder
	isgomock struct{}
}

// GoMockWriterMockRecorder is the mock recorder for GoMockWriter.
type GoMockWriterMockRecorder struct {
	mock *GoMockWriter
}

// NewGoMockWriter creates a new mock instance.
func NewGoMockWriter(ctrl *gomock.Controller) *GoMockWriter {
	mock := &GoMockWriter{ctrl: ctrl}
	mock.recorder = &GoMockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockWriter) EXPECT() *GoMockWriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *GoMockWriter) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *GoMockWriterMockRecorder) Write(p any) *GoMockWriterWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*GoMockWriter)(nil).Write), p)
	return &GoMockWriterWriteCall{Call: call}
}

// GoMockWriterWriteCall wrap *gomock.Call
type GoMockWriterWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriterWriteCall) Return(n int, err error) *GoMockWriterWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriterWriteCall) Do(f func([]byte) (int, error)) *GoMockWriterWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriterWriteCall) DoAndReturn(f func([]byte) (int, error)) *GoMockWriterWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockCloser is a mock of Closer interface.
type GoMockCloser struct {
	ctrl     *gomock.Controller
	recorder *GoMockCloserMockRecorder
	isgomock struct{}
}

// GoMockCloserMockRecorder is the mock recorder for GoMockCloser.
type GoMockCloserMockRecorder struct {
	mock *GoMockCloser
}

// NewGoMockCloser creates a new mock instance.
func NewGoMockCloser(ctrl *gomock.Controller) *GoMockCloser {
	mock := &GoMockCloser{ctrl: ctrl}
	mock.recorder = &GoMockCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockCloser) EXPECT() *GoMockCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *GoMockCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *GoMockCloserMockRecorder) Close() *GoMockCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*GoMockCloser)(nil).Close))
	return &GoMockCloserCloseCall{Call: call}
}

// GoMockCloserCloseCall wrap *gomock.Call
type GoMockCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockCloserCloseCall) Return(err error) *GoMockCloserCloseCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockCloserCloseCall) Do(f func() error) *GoMockCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockCloserCloseCall) DoAndReturn(f func() error) *GoMockCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockSeeker is a mock of Seeker interface.
type GoMockSeeker struct {
	ctrl     *gomock.Controller
	recorder *GoMockSeekerMockRecorder
	isgomock struct{}
}

// GoMockSeekerMockRecorder is the mock recorder for GoMockSeeker.
type GoMockSeekerMockRecorder struct {
	mock *GoMockSeeker
}

// NewGoMockSeeker creates a new mock instance.
func NewGoMockSeeker(ctrl *gomock.Controller) *GoMockSeeker {
	mock := &GoMockSeeker{ctrl: ctrl}
	mock.recorder = &GoMockSeekerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockSeeker) EXPECT() *GoMockSeekerMockRecorder {
	return m.recorder
}

// Seek mocks base method.
func (m *GoMockSeeker) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *GoMockSeekerMockRecorder) Seek(offset, whence any) *GoMockSeekerSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*GoMockSeeker)(nil).Seek), offset, whence)
	return &GoMockSeekerSeekCall{Call: call}
}

// GoMockSeekerSeekCall wrap *gomock.Call
type GoMockSeekerSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockSeekerSeekCall) Return(n int64, err error) *GoMockSeekerSeekCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockSeekerSeekCall) Do(f func(int64, int) (int64, error)) *GoMockSeekerSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockSeekerSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *GoMockSeekerSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReadWriter is a mock of ReadWriter interface.
type GoMockReadWriter struct {
	ctrl     *gomock.Controller
	recorder *GoMockReadWriterMockRecorder
	isgomock struct{}
}

// GoMockReadWriterMockRecorder is the mock recorder for GoMockReadWriter.
type GoMockReadWriterMockRecorder struct {
	mock *GoMockReadWriter
}

// NewGoMockReadWriter creates a new mock instance.
func NewGoMockReadWriter(ctrl *gomock.Controller) *GoMockReadWriter {
	mock := &GoMockReadWriter{ctrl: ctrl}
	mock.recorder = &GoMockReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReadWriter) EXPECT() *GoMockReadWriterMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *GoMockReadWriter) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReadWriterMockRecorder) Read(p any) *GoMockReadWriterReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReadWriter)(nil).Read), p)
	return &GoMockReadWriterReadCall{Call: call}
}

// GoMockReadWriterReadCall wrap *gomock.Call
type GoMockReadWriterReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriterReadCall) Return(n int, err error) *GoMockReadWriterReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriterReadCall) Do(f func([]byte) (int, error)) *GoMockReadWriterReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriterReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadWriterReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *GoMockReadWriter) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *GoMockReadWriterMockRecorder) Write(p any) *GoMockReadWriterWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*GoMockReadWriter)(nil).Write), p)
	return &GoMockReadWriterWriteCall{Call: call}
}

// GoMockReadWriterWriteCall wrap *gomock.Call
type GoMockReadWriterWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriterWriteCall) Return(n int, err error) *GoMockReadWriterWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriterWriteCall) Do(f func([]byte) (int, error)) *GoMockReadWriterWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriterWriteCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadWriterWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReadCloser is a mock of ReadCloser interface.
type GoMockReadCloser struct {
	ctrl     *gomock.Controller
	recorder *GoMockReadCloserMockRecorder
	isgomock struct{}
}

// GoMockReadCloserMockRecorder is the mock recorder for GoMockReadCloser.
type GoMockReadCloserMockRecorder struct {
	mock *GoMockReadCloser
}

// NewGoMockReadCloser creates a new mock instance.
func NewGoMockReadCloser(ctrl *gomock.Controller) *GoMockReadCloser {
	mock := &GoMockReadCloser{ctrl: ctrl}
	mock.recorder = &GoMockReadCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReadCloser) EXPECT() *GoMockReadCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *GoMockReadCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *GoMockReadCloserMockRecorder) Close() *GoMockReadCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*GoMockReadCloser)(nil).Close))
	return &GoMockReadCloserCloseCall{Call: call}
}

// GoMockReadCloserCloseCall wrap *gomock.Call
type GoMockReadCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadCloserCloseCall) Return(err error) *GoMockReadCloserCloseCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadCloserCloseCall) Do(f func() error) *GoMockReadCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadCloserCloseCall) DoAndReturn(f func() error) *GoMockReadCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *GoMockReadCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReadCloserMockRecorder) Read(p any) *GoMockReadCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReadCloser)(nil).Read), p)
	return &GoMockReadCloserReadCall{Call: call}
}

// GoMockReadCloserReadCall wrap *gomock.Call
type GoMockReadCloserReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadCloserReadCall) Return(n int, err error) *GoMockReadCloserReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadCloserReadCall) Do(f func([]byte) (int, error)) *GoMockReadCloserReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadCloserReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadCloserReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockWriteCloser is a mock of WriteCloser interface.
type GoMockWriteCloser struct {
	ctrl     *gomock.Controller
	recorder *GoMockWriteCloserMockRecorder
	isgomock struct{}
}

// GoMockWriteCloserMockRecorder is the mock recorder for GoMockWriteCloser.
type GoMockWriteCloserMockRecorder struct {
	mock *GoMockWriteCloser
}

// NewGoMockWriteCloser creates a new mock instance.
func NewGoMockWriteCloser(ctrl *gomock.Controller) *GoMockWriteCloser {
	mock := &GoMockWriteCloser{ctrl: ctrl}
	mock.recorder = &GoMockWriteCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockWriteCloser) EXPECT() *GoMockWriteCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *GoMockWriteCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *GoMockWriteCloserMockRecorder) Close() *GoMockWriteCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*GoMockWriteCloser)(nil).Close))
	return &GoMockWriteCloserCloseCall{Call: call}
}

// GoMockWriteCloserCloseCall wrap *gomock.Call
type GoMockWriteCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriteCloserCloseCall) Return(err error) *GoMockWriteCloserCloseCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriteCloserCloseCall) Do(f func() error) *GoMockWriteCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriteCloserCloseCall) DoAndReturn(f func() error) *GoMockWriteCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *GoMockWriteCloser) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *GoMockWriteCloserMockRecorder) Write(p any) *GoMockWriteCloserWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*GoMockWriteCloser)(nil).Write), p)
	return &GoMockWriteCloserWriteCall{Call: call}
}

// GoMockWriteCloserWriteCall wrap *gomock.Call
type GoMockWriteCloserWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriteCloserWriteCall) Return(n int, err error) *GoMockWriteCloserWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriteCloserWriteCall) Do(f func([]byte) (int, error)) *GoMockWriteCloserWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriteCloserWriteCall) DoAndReturn(f func([]byte) (int, error)) *GoMockWriteCloserWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReadWriteCloser is a mock of ReadWriteCloser interface.
type GoMockReadWriteCloser struct {
	ctrl     *gomock.Controller
	recorder *GoMockReadWriteCloserMockRecorder
	isgomock struct{}
}

// GoMockReadWriteCloserMockRecorder is the mock recorder for GoMockReadWriteCloser.
type GoMockReadWriteCloserMockRecorder struct {
	mock *GoMockReadWriteCloser
}

// NewGoMockReadWriteCloser creates a new mock instance.
func NewGoMockReadWriteCloser(ctrl *gomock.Controller) *GoMockReadWriteCloser {
	mock := &GoMockReadWriteCloser{ctrl: ctrl}
	mock.recorder = &GoMockReadWriteCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReadWriteCloser) EXPECT() *GoMockReadWriteCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *GoMockReadWriteCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *GoMockReadWriteCloserMockRecorder) Close() *GoMockReadWriteCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*GoMockReadWriteCloser)(nil).Close))
	return &GoMockReadWriteCloserCloseCall{Call: call}
}

// GoMockReadWriteCloserCloseCall wrap *gomock.Call
type GoMockReadWriteCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriteCloserCloseCall) Return(err error) *GoMockReadWriteCloserCloseCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriteCloserCloseCall) Do(f func() error) *GoMockReadWriteCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriteCloserCloseCall) DoAndReturn(f func() error) *GoMockReadWriteCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *GoMockReadWriteCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReadWriteCloserMockRecorder) Read(p any) *GoMockReadWriteCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReadWriteCloser)(nil).Read), p)
	return &GoMockReadWriteCloserReadCall{Call: call}
}

// GoMockReadWriteCloserReadCall wrap *gomock.Call
type GoMockReadWriteCloserReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriteCloserReadCall) Return(n int, err error) *GoMockReadWriteCloserReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriteCloserReadCall) Do(f func([]byte) (int, error)) *GoMockReadWriteCloserReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriteCloserReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadWriteCloserReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *GoMockReadWriteCloser) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *GoMockReadWriteCloserMockRecorder) Write(p any) *GoMockReadWriteCloserWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*GoMockReadWriteCloser)(nil).Write), p)
	return &GoMockReadWriteCloserWriteCall{Call: call}
}

// GoMockReadWriteCloserWriteCall wrap *gomock.Call
type GoMockReadWriteCloserWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriteCloserWriteCall) Return(n int, err error) *GoMockReadWriteCloserWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriteCloserWriteCall) Do(f func([]byte) (int, error)) *GoMockReadWriteCloserWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriteCloserWriteCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadWriteCloserWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReadSeeker is a mock of ReadSeeker interface.
type GoMockReadSeeker struct {
	ctrl     *gomock.Controller
	recorder *GoMockReadSeekerMockRecorder
	isgomock struct{}
}

// GoMockReadSeekerMockRecorder is the mock recorder for GoMockReadSeeker.
type GoMockReadSeekerMockRecorder struct {
	mock *GoMockReadSeeker
}

// NewGoMockReadSeeker creates a new mock instance.
func NewGoMockReadSeeker(ctrl *gomock.Controller) *GoMockReadSeeker {
	mock := &GoMockReadSeeker{ctrl: ctrl}
	mock.recorder = &GoMockReadSeekerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReadSeeker) EXPECT() *GoMockReadSeekerMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *GoMockReadSeeker) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReadSeekerMockRecorder) Read(p any) *GoMockReadSeekerReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReadSeeker)(nil).Read), p)
	return &GoMockReadSeekerReadCall{Call: call}
}

// GoMockReadSeekerReadCall wrap *gomock.Call
type GoMockReadSeekerReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadSeekerReadCall) Return(n int, err error) *GoMockReadSeekerReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadSeekerReadCall) Do(f func([]byte) (int, error)) *GoMockReadSeekerReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadSeekerReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadSeekerReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seek mocks base method.
func (m *GoMockReadSeeker) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *GoMockReadSeekerMockRecorder) Seek(offset, whence any) *GoMockReadSeekerSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*GoMockReadSeeker)(nil).Seek), offset, whence)
	return &GoMockReadSeekerSeekCall{Call: call}
}

// GoMockReadSeekerSeekCall wrap *gomock.Call
type GoMockReadSeekerSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadSeekerSeekCall) Return(n int64, err error) *GoMockReadSeekerSeekCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadSeekerSeekCall) Do(f func(int64, int) (int64, error)) *GoMockReadSeekerSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadSeekerSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *GoMockReadSeekerSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReadSeekCloser is a mock of ReadSeekCloser interface.
type GoMockReadSeekCloser struct {
	ctrl     *gomock.Controller
	recorder *GoMockReadSeekCloserMockRecorder
	isgomock struct{}
}

// GoMockReadSeekCloserMockRecorder is the mock recorder for GoMockReadSeekCloser.
type GoMockReadSeekCloserMockRecorder struct {
	mock *GoMockReadSeekCloser
}

// NewGoMockReadSeekCloser creates a new mock instance.
func NewGoMockReadSeekCloser(ctrl *gomock.Controller) *GoMockReadSeekCloser {
	mock := &GoMockReadSeekCloser{ctrl: ctrl}
	mock.recorder = &GoMockReadSeekCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReadSeekCloser) EXPECT() *GoMockReadSeekCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *GoMockReadSeekCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *GoMockReadSeekCloserMockRecorder) Close() *GoMockReadSeekCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*GoMockReadSeekCloser)(nil).Close))
	return &GoMockReadSeekCloserCloseCall{Call: call}
}

// GoMockReadSeekCloserCloseCall wrap *gomock.Call
type GoMockReadSeekCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadSeekCloserCloseCall) Return(err error) *GoMockReadSeekCloserCloseCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadSeekCloserCloseCall) Do(f func() error) *GoMockReadSeekCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadSeekCloserCloseCall) DoAndReturn(f func() error) *GoMockReadSeekCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *GoMockReadSeekCloser) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReadSeekCloserMockRecorder) Read(p any) *GoMockReadSeekCloserReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReadSeekCloser)(nil).Read), p)
	return &GoMockReadSeekCloserReadCall{Call: call}
}

// GoMockReadSeekCloserReadCall wrap *gomock.Call
type GoMockReadSeekCloserReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadSeekCloserReadCall) Return(n int, err error) *GoMockReadSeekCloserReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadSeekCloserReadCall) Do(f func([]byte) (int, error)) *GoMockReadSeekCloserReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadSeekCloserReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadSeekCloserReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seek mocks base method.
func (m *GoMockReadSeekCloser) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *GoMockReadSeekCloserMockRecorder) Seek(offset, whence any) *GoMockReadSeekCloserSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*GoMockReadSeekCloser)(nil).Seek), offset, whence)
	return &GoMockReadSeekCloserSeekCall{Call: call}
}

// GoMockReadSeekCloserSeekCall wrap *gomock.Call
type GoMockReadSeekCloserSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadSeekCloserSeekCall) Return(n int64, err error) *GoMockReadSeekCloserSeekCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadSeekCloserSeekCall) Do(f func(int64, int) (int64, error)) *GoMockReadSeekCloserSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadSeekCloserSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *GoMockReadSeekCloserSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockWriteSeeker is a mock of WriteSeeker interface.
type GoMockWriteSeeker struct {
	ctrl     *gomock.Controller
	recorder *GoMockWriteSeekerMockRecorder
	isgomock struct{}
}

// GoMockWriteSeekerMockRecorder is the mock recorder for GoMockWriteSeeker.
type GoMockWriteSeekerMockRecorder struct {
	mock *GoMockWriteSeeker
}

// NewGoMockWriteSeeker creates a new mock instance.
func NewGoMockWriteSeeker(ctrl *gomock.Controller) *GoMockWriteSeeker {
	mock := &GoMockWriteSeeker{ctrl: ctrl}
	mock.recorder = &GoMockWriteSeekerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockWriteSeeker) EXPECT() *GoMockWriteSeekerMockRecorder {
	return m.recorder
}

// Seek mocks base method.
func (m *GoMockWriteSeeker) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *GoMockWriteSeekerMockRecorder) Seek(offset, whence any) *GoMockWriteSeekerSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*GoMockWriteSeeker)(nil).Seek), offset, whence)
	return &GoMockWriteSeekerSeekCall{Call: call}
}

// GoMockWriteSeekerSeekCall wrap *gomock.Call
type GoMockWriteSeekerSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriteSeekerSeekCall) Return(n int64, err error) *GoMockWriteSeekerSeekCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriteSeekerSeekCall) Do(f func(int64, int) (int64, error)) *GoMockWriteSeekerSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriteSeekerSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *GoMockWriteSeekerSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *GoMockWriteSeeker) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *GoMockWriteSeekerMockRecorder) Write(p any) *GoMockWriteSeekerWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*GoMockWriteSeeker)(nil).Write), p)
	return &GoMockWriteSeekerWriteCall{Call: call}
}

// GoMockWriteSeekerWriteCall wrap *gomock.Call
type GoMockWriteSeekerWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriteSeekerWriteCall) Return(n int, err error) *GoMockWriteSeekerWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriteSeekerWriteCall) Do(f func([]byte) (int, error)) *GoMockWriteSeekerWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriteSeekerWriteCall) DoAndReturn(f func([]byte) (int, error)) *GoMockWriteSeekerWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReadWriteSeeker is a mock of ReadWriteSeeker interface.
type GoMockReadWriteSeeker struct {
	ctrl     *gomock.Controller
	recorder *GoMockReadWriteSeekerMockRecorder
	isgomock struct{}
}

// GoMockReadWriteSeekerMockRecorder is the mock recorder for GoMockReadWriteSeeker.
type GoMockReadWriteSeekerMockRecorder struct {
	mock *GoMockReadWriteSeeker
}

// NewGoMockReadWriteSeeker creates a new mock instance.
func NewGoMockReadWriteSeeker(ctrl *gomock.Controller) *GoMockReadWriteSeeker {
	mock := &GoMockReadWriteSeeker{ctrl: ctrl}
	mock.recorder = &GoMockReadWriteSeekerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReadWriteSeeker) EXPECT() *GoMockReadWriteSeekerMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *GoMockReadWriteSeeker) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *GoMockReadWriteSeekerMockRecorder) Read(p any) *GoMockReadWriteSeekerReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*GoMockReadWriteSeeker)(nil).Read), p)
	return &GoMockReadWriteSeekerReadCall{Call: call}
}

// GoMockReadWriteSeekerReadCall wrap *gomock.Call
type GoMockReadWriteSeekerReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriteSeekerReadCall) Return(n int, err error) *GoMockReadWriteSeekerReadCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriteSeekerReadCall) Do(f func([]byte) (int, error)) *GoMockReadWriteSeekerReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriteSeekerReadCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadWriteSeekerReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seek mocks base method.
func (m *GoMockReadWriteSeeker) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *GoMockReadWriteSeekerMockRecorder) Seek(offset, whence any) *GoMockReadWriteSeekerSeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*GoMockReadWriteSeeker)(nil).Seek), offset, whence)
	return &GoMockReadWriteSeekerSeekCall{Call: call}
}

// GoMockReadWriteSeekerSeekCall wrap *gomock.Call
type GoMockReadWriteSeekerSeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriteSeekerSeekCall) Return(n int64, err error) *GoMockReadWriteSeekerSeekCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriteSeekerSeekCall) Do(f func(int64, int) (int64, error)) *GoMockReadWriteSeekerSeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriteSeekerSeekCall) DoAndReturn(f func(int64, int) (int64, error)) *GoMockReadWriteSeekerSeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Write mocks base method.
func (m *GoMockReadWriteSeeker) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *GoMockReadWriteSeekerMockRecorder) Write(p any) *GoMockReadWriteSeekerWriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*GoMockReadWriteSeeker)(nil).Write), p)
	return &GoMockReadWriteSeekerWriteCall{Call: call}
}

// GoMockReadWriteSeekerWriteCall wrap *gomock.Call
type GoMockReadWriteSeekerWriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReadWriteSeekerWriteCall) Return(n int, err error) *GoMockReadWriteSeekerWriteCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReadWriteSeekerWriteCall) Do(f func([]byte) (int, error)) *GoMockReadWriteSeekerWriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReadWriteSeekerWriteCall) DoAndReturn(f func([]byte) (int, error)) *GoMockReadWriteSeekerWriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReaderFrom is a mock of ReaderFrom interface.
type GoMockReaderFrom struct {
	ctrl     *gomock.Controller
	recorder *GoMockReaderFromMockRecorder
	isgomock struct{}
}

// GoMockReaderFromMockRecorder is the mock recorder for GoMockReaderFrom.
type GoMockReaderFromMockRecorder struct {
	mock *GoMockReaderFrom
}

// NewGoMockReaderFrom creates a new mock instance.
func NewGoMockReaderFrom(ctrl *gomock.Controller) *GoMockReaderFrom {
	mock := &GoMockReaderFrom{ctrl: ctrl}
	mock.recorder = &GoMockReaderFromMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReaderFrom) EXPECT() *GoMockReaderFromMockRecorder {
	return m.recorder
}

// ReadFrom mocks base method.
func (m *GoMockReaderFrom) ReadFrom(r io.Reader) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFrom", r)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFrom indicates an expected call of ReadFrom.
func (mr *GoMockReaderFromMockRecorder) ReadFrom(r any) *GoMockReaderFromReadFromCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFrom", reflect.TypeOf((*GoMockReaderFrom)(nil).ReadFrom), r)
	return &GoMockReaderFromReadFromCall{Call: call}
}

// GoMockReaderFromReadFromCall wrap *gomock.Call
type GoMockReaderFromReadFromCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReaderFromReadFromCall) Return(n int64, err error) *GoMockReaderFromReadFromCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReaderFromReadFromCall) Do(f func(io.Reader) (int64, error)) *GoMockReaderFromReadFromCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReaderFromReadFromCall) DoAndReturn(f func(io.Reader) (int64, error)) *GoMockReaderFromReadFromCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockWriterTo is a mock of WriterTo interface.
type GoMockWriterTo struct {
	ctrl     *gomock.Controller
	recorder *GoMockWriterToMockRecorder
	isgomock struct{}
}

// GoMockWriterToMockRecorder is the mock recorder for GoMockWriterTo.
type GoMockWriterToMockRecorder struct {
	mock *GoMockWriterTo
}

// NewGoMockWriterTo creates a new mock instance.
func NewGoMockWriterTo(ctrl *gomock.Controller) *GoMockWriterTo {
	mock := &GoMockWriterTo{ctrl: ctrl}
	mock.recorder = &GoMockWriterToMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockWriterTo) EXPECT() *GoMockWriterToMockRecorder {
	return m.recorder
}

// WriteTo mocks base method.
func (m *GoMockWriterTo) WriteTo(w io.Writer) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTo", w)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteTo indicates an expected call of WriteTo.
func (mr *GoMockWriterToMockRecorder) WriteTo(w any) *GoMockWriterToWriteToCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTo", reflect.TypeOf((*GoMockWriterTo)(nil).WriteTo), w)
	return &GoMockWriterToWriteToCall{Call: call}
}

// GoMockWriterToWriteToCall wrap *gomock.Call
type GoMockWriterToWriteToCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriterToWriteToCall) Return(n int64, err error) *GoMockWriterToWriteToCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriterToWriteToCall) Do(f func(io.Writer) (int64, error)) *GoMockWriterToWriteToCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriterToWriteToCall) DoAndReturn(f func(io.Writer) (int64, error)) *GoMockWriterToWriteToCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockReaderAt is a mock of ReaderAt interface.
type GoMockReaderAt struct {
	ctrl     *gomock.Controller
	recorder *GoMockReaderAtMockRecorder
	isgomock struct{}
}

// GoMockReaderAtMockRecorder is the mock recorder for GoMockReaderAt.
type GoMockReaderAtMockRecorder struct {
	mock *GoMockReaderAt
}

// NewGoMockReaderAt creates a new mock instance.
func NewGoMockReaderAt(ctrl *gomock.Controller) *GoMockReaderAt {
	mock := &GoMockReaderAt{ctrl: ctrl}
	mock.recorder = &GoMockReaderAtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockReaderAt) EXPECT() *GoMockReaderAtMockRecorder {
	return m.recorder
}

// ReadAt mocks base method.
func (m *GoMockReaderAt) ReadAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAt indicates an expected call of ReadAt.
func (mr *GoMockReaderAtMockRecorder) ReadAt(p, off any) *GoMockReaderAtReadAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAt", reflect.TypeOf((*GoMockReaderAt)(nil).ReadAt), p, off)
	return &GoMockReaderAtReadAtCall{Call: call}
}

// GoMockReaderAtReadAtCall wrap *gomock.Call
type GoMockReaderAtReadAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockReaderAtReadAtCall) Return(n int, err error) *GoMockReaderAtReadAtCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockReaderAtReadAtCall) Do(f func([]byte, int64) (int, error)) *GoMockReaderAtReadAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockReaderAtReadAtCall) DoAndReturn(f func([]byte, int64) (int, error)) *GoMockReaderAtReadAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockWriterAt is a mock of WriterAt interface.
type GoMockWriterAt struct {
	ctrl     *gomock.Controller
	recorder *GoMockWriterAtMockRecorder
	isgomock struct{}
}

// GoMockWriterAtMockRecorder is the mock recorder for GoMockWriterAt.
type GoMockWriterAtMockRecorder struct {
	mock *GoMockWriterAt
}

// NewGoMockWriterAt creates a new mock instance.
func NewGoMockWriterAt(ctrl *gomock.Controller) *GoMockWriterAt {
	mock := &GoMockWriterAt{ctrl: ctrl}
	mock.recorder = &GoMockWriterAtMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockWriterAt) EXPECT() *GoMockWriterAtMockRecorder {
	return m.recorder
}

// WriteAt mocks base method.
func (m *GoMockWriterAt) WriteAt(p []byte, off int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAt", p, off)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteAt indicates an expected call of WriteAt.
func (mr *GoMockWriterAtMockRecorder) WriteAt(p, off any) *GoMockWriterAtWriteAtCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAt", reflect.TypeOf((*GoMockWriterAt)(nil).WriteAt), p, off)
	return &GoMockWriterAtWriteAtCall{Call: call}
}

// GoMockWriterAtWriteAtCall wrap *gomock.Call
type GoMockWriterAtWriteAtCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockWriterAtWriteAtCall) Return(n int, err error) *GoMockWriterAtWriteAtCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockWriterAtWriteAtCall) Do(f func([]byte, int64) (int, error)) *GoMockWriterAtWriteAtCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockWriterAtWriteAtCall) DoAndReturn(f func([]byte, int64) (int, error)) *GoMockWriterAtWriteAtCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockByteReader is a mock of ByteReader interface.
type GoMockByteReader struct {
	ctrl     *gomock.Controller
	recorder *GoMockByteReaderMockRecorder
	isgomock struct{}
}

// GoMockByteReaderMockRecorder is the mock recorder for GoMockByteReader.
type GoMockByteReaderMockRecorder struct {
	mock *GoMockByteReader
}

// NewGoMockByteReader creates a new mock instance.
func NewGoMockByteReader(ctrl *gomock.Controller) *GoMockByteReader {
	mock := &GoMockByteReader{ctrl: ctrl}
	mock.recorder = &GoMockByteReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockByteReader) EXPECT() *GoMockByteReaderMockRecorder {
	return m.recorder
}

// ReadByte mocks base method.
func (m *GoMockByteReader) ReadByte() (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByte")
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByte indicates an expected call of ReadByte.
func (mr *GoMockByteReaderMockRecorder) ReadByte() *GoMockByteReaderReadByteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByte", reflect.TypeOf((*GoMockByteReader)(nil).ReadByte))
	return &GoMockByteReaderReadByteCall{Call: call}
}

// GoMockByteReaderReadByteCall wrap *gomock.Call
type GoMockByteReaderReadByteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockByteReaderReadByteCall) Return(v byte, err error) *GoMockByteReaderReadByteCall {
	c.Call = c.Call.Return(v, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockByteReaderReadByteCall) Do(f func() (byte, error)) *GoMockByteReaderReadByteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockByteReaderReadByteCall) DoAndReturn(f func() (byte, error)) *GoMockByteReaderReadByteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockByteScanner is a mock of ByteScanner interface.
type GoMockByteScanner struct {
	ctrl     *gomock.Controller
	recorder *GoMockByteScannerMockRecorder
	isgomock struct{}
}

// GoMockByteScannerMockRecorder is the mock recorder for GoMockByteScanner.
type GoMockByteScannerMockRecorder struct {
	mock *GoMockByteScanner
}

// NewGoMockByteScanner creates a new mock instance.
func NewGoMockByteScanner(ctrl *gomock.Controller) *GoMockByteScanner {
	mock := &GoMockByteScanner{ctrl: ctrl}
	mock.recorder = &GoMockByteScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockByteScanner) EXPECT() *GoMockByteScannerMockRecorder {
	return m.recorder
}

// ReadByte mocks base method.
func (m *GoMockByteScanner) ReadByte() (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByte")
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByte indicates an expected call of ReadByte.
func (mr *GoMockByteScannerMockRecorder) ReadByte() *GoMockByteScannerReadByteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByte", reflect.TypeOf((*GoMockByteScanner)(nil).ReadByte))
	return &GoMockByteScannerReadByteCall{Call: call}
}

// GoMockByteScannerReadByteCall wrap *gomock.Call
type GoMockByteScannerReadByteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockByteScannerReadByteCall) Return(v byte, err error) *GoMockByteScannerReadByteCall {
	c.Call = c.Call.Return(v, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockByteScannerReadByteCall) Do(f func() (byte, error)) *GoMockByteScannerReadByteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockByteScannerReadByteCall) DoAndReturn(f func() (byte, error)) *GoMockByteScannerReadByteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnreadByte mocks base method.
func (m *GoMockByteScanner) UnreadByte() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadByte")
	ret0, _ := ret[0].(error)
	return ret0
}

// UnreadByte indicates an expected call of UnreadByte.
func (mr *GoMockByteScannerMockRecorder) UnreadByte() *GoMockByteScannerUnreadByteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadByte", reflect.TypeOf((*GoMockByteScanner)(nil).UnreadByte))
	return &GoMockByteScannerUnreadByteCall{Call: call}
}

// GoMockByteScannerUnreadByteCall wrap *gomock.Call
type GoMockByteScannerUnreadByteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockByteScannerUnreadByteCall) Return(err error) *GoMockByteScannerUnreadByteCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockByteScannerUnreadByteCall) Do(f func() error) *GoMockByteScannerUnreadByteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockByteScannerUnreadByteCall) DoAndReturn(f func() error) *GoMockByteScannerUnreadByteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockByteWriter is a mock of ByteWriter interface.
type GoMockByteWriter struct {
	ctrl     *gomock.Controller
	recorder *GoMockByteWriterMockRecorder
	isgomock struct{}
}

// GoMockByteWriterMockRecorder is the mock recorder for GoMockByteWriter.
type GoMockByteWriterMockRecorder struct {
	mock *GoMockByteWriter
}

// NewGoMockByteWriter creates a new mock instance.
func NewGoMockByteWriter(ctrl *gomock.Controller) *GoMockByteWriter {
	mock := &GoMockByteWriter{ctrl: ctrl}
	mock.recorder = &GoMockByteWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockByteWriter) EXPECT() *GoMockByteWriterMockRecorder {
	return m.recorder
}

// WriteByte mocks base method.
func (m *GoMockByteWriter) WriteByte(c byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteByte", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteByte indicates an expected call of WriteByte.
func (mr *GoMockByteWriterMockRecorder) WriteByte(c any) *GoMockByteWriterWriteByteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteByte", reflect.TypeOf((*GoMockByteWriter)(nil).WriteByte), c)
	return &GoMockByteWriterWriteByteCall{Call: call}
}

// GoMockByteWriterWriteByteCall wrap *gomock.Call
type GoMockByteWriterWriteByteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c1 *GoMockByteWriterWriteByteCall) Return(err error) *GoMockByteWriterWriteByteCall {
	c1.Call = c1.Call.Return(err)
	return c1
}

// Do rewrite *gomock.Call.Do
func (c1 *GoMockByteWriterWriteByteCall) Do(f func(byte) error) *GoMockByteWriterWriteByteCall {
	c1.Call = c1.Call.Do(f)
	return c1
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c1 *GoMockByteWriterWriteByteCall) DoAndReturn(f func(byte) error) *GoMockByteWriterWriteByteCall {
	c1.Call = c1.Call.DoAndReturn(f)
	return c1
}

// GoMockRuneReader is a mock of RuneReader interface.
type GoMockRuneReader struct {
	ctrl     *gomock.Controller
	recorder *GoMockRuneReaderMockRecorder
	isgomock struct{}
}

// GoMockRuneReaderMockRecorder is the mock recorder for GoMockRuneReader.
type GoMockRuneReaderMockRecorder struct {
	mock *GoMockRuneReader
}

// NewGoMockRuneReader creates a new mock instance.
func NewGoMockRuneReader(ctrl *gomock.Controller) *GoMockRuneReader {
	mock := &GoMockRuneReader{ctrl: ctrl}
	mock.recorder = &GoMockRuneReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockRuneReader) EXPECT() *GoMockRuneReaderMockRecorder {
	return m.recorder
}

// ReadRune mocks base method.
func (m *GoMockRuneReader) ReadRune() (rune, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRune")
	ret0, _ := ret[0].(rune)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadRune indicates an expected call of ReadRune.
func (mr *GoMockRuneReaderMockRecorder) ReadRune() *GoMockRuneReaderReadRuneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRune", reflect.TypeOf((*GoMockRuneReader)(nil).ReadRune))
	return &GoMockRuneReaderReadRuneCall{Call: call}
}

// GoMockRuneReaderReadRuneCall wrap *gomock.Call
type GoMockRuneReaderReadRuneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockRuneReaderReadRuneCall) Return(r rune, size int, err error) *GoMockRuneReaderReadRuneCall {
	c.Call = c.Call.Return(r, size, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockRuneReaderReadRuneCall) Do(f func() (rune, int, error)) *GoMockRuneReaderReadRuneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockRuneReaderReadRuneCall) DoAndReturn(f func() (rune, int, error)) *GoMockRuneReaderReadRuneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockRuneScanner is a mock of RuneScanner interface.
type GoMockRuneScanner struct {
	ctrl     *gomock.Controller
	recorder *GoMockRuneScannerMockRecorder
	isgomock struct{}
}

// GoMockRuneScannerMockRecorder is the mock recorder for GoMockRuneScanner.
type GoMockRuneScannerMockRecorder struct {
	mock *GoMockRuneScanner
}

// NewGoMockRuneScanner creates a new mock instance.
func NewGoMockRuneScanner(ctrl *gomock.Controller) *GoMockRuneScanner {
	mock := &GoMockRuneScanner{ctrl: ctrl}
	mock.recorder = &GoMockRuneScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockRuneScanner) EXPECT() *GoMockRuneScannerMockRecorder {
	return m.recorder
}

// ReadRune mocks base method.
func (m *GoMockRuneScanner) ReadRune() (rune, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRune")
	ret0, _ := ret[0].(rune)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadRune indicates an expected call of ReadRune.
func (mr *GoMockRuneScannerMockRecorder) ReadRune() *GoMockRuneScannerReadRuneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRune", reflect.TypeOf((*GoMockRuneScanner)(nil).ReadRune))
	return &GoMockRuneScannerReadRuneCall{Call: call}
}

// GoMockRuneScannerReadRuneCall wrap *gomock.Call
type GoMockRuneScannerReadRuneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockRuneScannerReadRuneCall) Return(r rune, size int, err error) *GoMockRuneScannerReadRuneCall {
	c.Call = c.Call.Return(r, size, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockRuneScannerReadRuneCall) Do(f func() (rune, int, error)) *GoMockRuneScannerReadRuneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockRuneScannerReadRuneCall) DoAndReturn(f func() (rune, int, error)) *GoMockRuneScannerReadRuneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnreadRune mocks base method.
func (m *GoMockRuneScanner) UnreadRune() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadRune")
	ret0, _ := ret[0].(error)
	return ret0
}

// UnreadRune indicates an expected call of UnreadRune.
func (mr *GoMockRuneScannerMockRecorder) UnreadRune() *GoMockRuneScannerUnreadRuneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadRune", reflect.TypeOf((*GoMockRuneScanner)(nil).UnreadRune))
	return &GoMockRuneScannerUnreadRuneCall{Call: call}
}

// GoMockRuneScannerUnreadRuneCall wrap *gomock.Call
type GoMockRuneScannerUnreadRuneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockRuneScannerUnreadRuneCall) Return(err error) *GoMockRuneScannerUnreadRuneCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockRuneScannerUnreadRuneCall) Do(f func() error) *GoMockRuneScannerUnreadRuneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockRuneScannerUnreadRuneCall) DoAndReturn(f func() error) *GoMockRuneScannerUnreadRuneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GoMockStringWriter is a mock of StringWriter interface.
type GoMockStringWriter struct {
	ctrl     *gomock.Controller
	recorder *GoMockStringWriterMockRecorder
	isgomock struct{}
}

// GoMockStringWriterMockRecorder is the mock recorder for GoMockStringWriter.
type GoMockStringWriterMockRecorder struct {
	mock *GoMockStringWriter
}

// NewGoMockStringWriter creates a new mock instance.
func NewGoMockStringWriter(ctrl *gomock.Controller) *GoMockStringWriter {
	mock := &GoMockStringWriter{ctrl: ctrl}
	mock.recorder = &GoMockStringWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *GoMockStringWriter) EXPECT() *GoMockStringWriterMockRecorder {
	return m.recorder
}

// WriteString mocks base method.
func (m *GoMockStringWriter) WriteString(s string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteString", s)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteString indicates an expected call of WriteString.
func (mr *GoMockStringWriterMockRecorder) WriteString(s any) *GoMockStringWriterWriteStringCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteString", reflect.TypeOf((*GoMockStringWriter)(nil).WriteString), s)
	return &GoMockStringWriterWriteStringCall{Call: call}
}

// GoMockStringWriterWriteStringCall wrap *gomock.Call
type GoMockStringWriterWriteStringCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *GoMockStringWriterWriteStringCall) Return(n int, err error) *GoMockStringWriterWriteStringCall {
	c.Call = c.Call.Return(n, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *GoMockStringWriterWriteStringCall) Do(f func(string) (int, error)) *GoMockStringWriterWriteStringCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *GoMockStringWriterWriteStringCall) DoAndReturn(f func(string) (int, error)) *GoMockStringWriterWriteStringCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
