// TEST MOCKERY BOILERPLATE

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package replace_type_pointers

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInterfaceWithPointers creates a new instance of MockInterfaceWithPointers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterfaceWithPointers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterfaceWithPointers {
	mock := &MockInterfaceWithPointers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterfaceWithPointers is an autogenerated mock type for the InterfaceWithPointers type
type MockInterfaceWithPointers struct {
	mock.Mock
}

type MockInterfaceWithPointers_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterfaceWithPointers) EXPECT() *MockInterfaceWithPointers_Expecter {
	return &MockInterfaceWithPointers_Expecter{mock: &_m.Mock}
}

// BarFunc provides a mock function for the type MockInterfaceWithPointers
func (_mock *MockInterfaceWithPointers) BarFunc(bar Bar) Bar {
	ret := _mock.Called(bar)

	if len(ret) == 0 {
		panic("no return value specified for BarFunc")
	}

	var r0 Bar
	if returnFunc, ok := ret.Get(0).(func(Bar) Bar); ok {
		r0 = returnFunc(bar)
	} else {
		r0 = ret.Get(0).(Bar)
	}
	return r0
}

// MockInterfaceWithPointers_BarFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BarFunc'
type MockInterfaceWithPointers_BarFunc_Call struct {
	*mock.Call
}

// BarFunc is a helper method to define mock.On call
//   - bar Bar
func (_e *MockInterfaceWithPointers_Expecter) BarFunc(bar any) *MockInterfaceWithPointers_BarFunc_Call {
	return &MockInterfaceWithPointers_BarFunc_Call{Call: _e.mock.On("BarFunc", bar)}
}

func (_c *MockInterfaceWithPointers_BarFunc_Call) Run(run func(bar Bar)) *MockInterfaceWithPointers_BarFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Bar
		if args[0] != nil {
			arg0 = args[0].(Bar)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterfaceWithPointers_BarFunc_Call) Return(bar1 Bar) *MockInterfaceWithPointers_BarFunc_Call {
	_c.Call.Return(bar1)
	return _c
}

func (_c *MockInterfaceWithPointers_BarFunc_Call) RunAndReturn(run func(bar Bar) Bar) *MockInterfaceWithPointers_BarFunc_Call {
	_c.Call.Return(run)
	return _c
}

// FooFunc provides a mock function for the type MockInterfaceWithPointers
func (_mock *MockInterfaceWithPointers) FooFunc(foo *Bar) *Bar {
	ret := _mock.Called(foo)

	if len(ret) == 0 {
		panic("no return value specified for FooFunc")
	}

	var r0 *Bar
	if returnFunc, ok := ret.Get(0).(func(*Bar) *Bar); ok {
		r0 = returnFunc(foo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Bar)
		}
	}
	return r0
}

// MockInterfaceWithPointers_FooFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FooFunc'
type MockInterfaceWithPointers_FooFunc_Call struct {
	*mock.Call
}

// FooFunc is a helper method to define mock.On call
//   - foo *Bar
func (_e *MockInterfaceWithPointers_Expecter) FooFunc(foo any) *MockInterfaceWithPointers_FooFunc_Call {
	return &MockInterfaceWithPointers_FooFunc_Call{Call: _e.mock.On("FooFunc", foo)}
}

func (_c *MockInterfaceWithPointers_FooFunc_Call) Run(run func(foo *Bar)) *MockInterfaceWithPointers_FooFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Bar
		if args[0] != nil {
			arg0 = args[0].(*Bar)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInterfaceWithPointers_FooFunc_Call) Return(foo1 *Bar) *MockInterfaceWithPointers_FooFunc_Call {
	_c.Call.Return(foo1)
	return _c
}

func (_c *MockInterfaceWithPointers_FooFunc_Call) RunAndReturn(run func(foo *Bar) *Bar) *MockInterfaceWithPointers_FooFunc_Call {
	_c.Call.Return(run)
	return _c
}
