// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	mockery "github.com/vektra/mockery/pkg/mockery"
)

// WalkerVisitor is an autogenerated mock type for the WalkerVisitor type
type WalkerVisitor struct {
	mock.Mock
}

// VisitWalk provides a mock function with given fields: _a0, _a1
func (_m *WalkerVisitor) VisitWalk(_a0 context.Context, _a1 *mockery.Interface) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *mockery.Interface) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
