// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package testfoo

import (
	"sync"

	test "github.com/vektra/mockery/v2/pkg/fixtures"
)

// Ensure, that Requester3 does implement test.Requester3.
// If this is not the case, regenerate this file with moq.
var _ test.Requester3 = &Requester3{}

// Requester3 is a mock implementation of test.Requester3.
//
//	func TestSomethingThatUsesRequester3(t *testing.T) {
//
//		// make and configure a mocked test.Requester3
//		mockedRequester3 := &Requester3{
//			GetFunc: func() error {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedRequester3 in code that requires test.Requester3
//		// and then make assertions.
//
//	}
type Requester3 struct {
	// GetFunc mocks the Get method.
	GetFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *Requester3) Get() error {
	if mock.GetFunc == nil {
		panic("Requester3.GetFunc: method is nil but Requester3.Get was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc()
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRequester3.GetCalls())
func (mock *Requester3) GetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
