// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package test

import (
	"encoding/json"
	"sync"
)

// RequesterArgSameAsImport is a mock implementation of RequesterArgSameAsImport.
//
//	func TestSomethingThatUsesRequesterArgSameAsImport(t *testing.T) {
//
//		// make and configure a mocked RequesterArgSameAsImport
//		mockedRequesterArgSameAsImport := &RequesterArgSameAsImport{
//			GetFunc: func(jsonMoqParam string) *json.RawMessage {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedRequesterArgSameAsImport in code that requires RequesterArgSameAsImport
//		// and then make assertions.
//
//	}
type RequesterArgSameAsImport struct {
	// GetFunc mocks the Get method.
	GetFunc func(jsonMoqParam string) *json.RawMessage

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// JsonMoqParam is the jsonMoqParam argument value.
			JsonMoqParam string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *RequesterArgSameAsImport) Get(jsonMoqParam string) *json.RawMessage {
	if mock.GetFunc == nil {
		panic("RequesterArgSameAsImport.GetFunc: method is nil but RequesterArgSameAsImport.Get was just called")
	}
	callInfo := struct {
		JsonMoqParam string
	}{
		JsonMoqParam: jsonMoqParam,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(jsonMoqParam)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRequesterArgSameAsImport.GetCalls())
func (mock *RequesterArgSameAsImport) GetCalls() []struct {
	JsonMoqParam string
} {
	var calls []struct {
		JsonMoqParam string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *RequesterArgSameAsImport) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *RequesterArgSameAsImport) ResetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}
