// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package test

import (
	"sync"
)

// RequesterPtrMock is a mock implementation of RequesterPtr.
//
//	func TestSomethingThatUsesRequesterPtr(t *testing.T) {
//
//		// make and configure a mocked RequesterPtr
//		mockedRequesterPtr := &RequesterPtrMock{
//			GetFunc: func(path string) (*string, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedRequesterPtr in code that requires RequesterPtr
//		// and then make assertions.
//
//	}
type RequesterPtrMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(path string) (*string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Path is the path argument value.
			Path string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *RequesterPtrMock) Get(path string) (*string, error) {
	if mock.GetFunc == nil {
		panic("RequesterPtrMock.GetFunc: method is nil but RequesterPtr.Get was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(path)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRequesterPtr.GetCalls())
func (mock *RequesterPtrMock) GetCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *RequesterPtrMock) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *RequesterPtrMock) ResetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}
