// Code generated by B2H-MockGen v0.0.0-dev. EDIT AT YOUR OWN PERIL.

package b2hmock

import mock "github.com/stretchr/testify/mock"

type IfaceWithBuildTagInCommentMock struct {
	mock.Mock
}

func (_m *IfaceWithBuildTagInCommentMock) Sprintf(format string, a ...interface{}) string {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, a...)
	args := _m.Called(_ca...)
	return args.Get(0).(string)
}
