// TEST MOCKERY BOILERPLATE

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package directive_comments

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewFunServerWithDifferentFile creates a new instance of FunServerWithDifferentFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFunServerWithDifferentFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *FunServerWithDifferentFile {
	mock := &FunServerWithDifferentFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FunServerWithDifferentFile is an autogenerated mock type for the ServerWithDifferentFile type
type FunServerWithDifferentFile struct {
	mock.Mock
}

type FunServerWithDifferentFile_Expecter struct {
	mock *mock.Mock
}

func (_m *FunServerWithDifferentFile) EXPECT() *FunServerWithDifferentFile_Expecter {
	return &FunServerWithDifferentFile_Expecter{mock: &_m.Mock}
}

// HandleRequest provides a mock function for the type FunServerWithDifferentFile
func (_mock *FunServerWithDifferentFile) HandleRequest(path string, handler http.Handler) {
	_mock.Called(path, handler)
	return
}

// FunServerWithDifferentFile_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type FunServerWithDifferentFile_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - path string
//   - handler http.Handler
func (_e *FunServerWithDifferentFile_Expecter) HandleRequest(path any, handler any) *FunServerWithDifferentFile_HandleRequest_Call {
	return &FunServerWithDifferentFile_HandleRequest_Call{Call: _e.mock.On("HandleRequest", path, handler)}
}

func (_c *FunServerWithDifferentFile_HandleRequest_Call) Run(run func(path string, handler http.Handler)) *FunServerWithDifferentFile_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.Handler
		if args[1] != nil {
			arg1 = args[1].(http.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FunServerWithDifferentFile_HandleRequest_Call) Return() *FunServerWithDifferentFile_HandleRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *FunServerWithDifferentFile_HandleRequest_Call) RunAndReturn(run func(path string, handler http.Handler)) *FunServerWithDifferentFile_HandleRequest_Call {
	_c.Run(run)
	return _c
}

// NewAnotherFunServerWithDifferentFile creates a new instance of AnotherFunServerWithDifferentFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnotherFunServerWithDifferentFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnotherFunServerWithDifferentFile {
	mock := &AnotherFunServerWithDifferentFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AnotherFunServerWithDifferentFile is an autogenerated mock type for the ServerWithDifferentFile type
type AnotherFunServerWithDifferentFile struct {
	mock.Mock
}

type AnotherFunServerWithDifferentFile_Expecter struct {
	mock *mock.Mock
}

func (_m *AnotherFunServerWithDifferentFile) EXPECT() *AnotherFunServerWithDifferentFile_Expecter {
	return &AnotherFunServerWithDifferentFile_Expecter{mock: &_m.Mock}
}

// HandleRequest provides a mock function for the type AnotherFunServerWithDifferentFile
func (_mock *AnotherFunServerWithDifferentFile) HandleRequest(path string, handler http.Handler) {
	_mock.Called(path, handler)
	return
}

// AnotherFunServerWithDifferentFile_HandleRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRequest'
type AnotherFunServerWithDifferentFile_HandleRequest_Call struct {
	*mock.Call
}

// HandleRequest is a helper method to define mock.On call
//   - path string
//   - handler http.Handler
func (_e *AnotherFunServerWithDifferentFile_Expecter) HandleRequest(path any, handler any) *AnotherFunServerWithDifferentFile_HandleRequest_Call {
	return &AnotherFunServerWithDifferentFile_HandleRequest_Call{Call: _e.mock.On("HandleRequest", path, handler)}
}

func (_c *AnotherFunServerWithDifferentFile_HandleRequest_Call) Run(run func(path string, handler http.Handler)) *AnotherFunServerWithDifferentFile_HandleRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.Handler
		if args[1] != nil {
			arg1 = args[1].(http.Handler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AnotherFunServerWithDifferentFile_HandleRequest_Call) Return() *AnotherFunServerWithDifferentFile_HandleRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnotherFunServerWithDifferentFile_HandleRequest_Call) RunAndReturn(run func(path string, handler http.Handler)) *AnotherFunServerWithDifferentFile_HandleRequest_Call {
	_c.Run(run)
	return _c
}
