// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// namer is an autogenerated mock type for the namer type
type namer struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *namer) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// newNamer creates a new instance of namer. It also registers a cleanup function to assert the mocks expectations.
func newNamer(t testing.TB) *namer {
	mock := &namer{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
