// TEST MOCKERY BOILERPLATE

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package skipensuremocks

import (
	"sync"

	"github.com/vektra/mockery/v3/internal/fixtures/matryer_skip_ensure/skip"
)

// Ensure that MoqFirstMixed does implement skip.First.
// If this is not the case, regenerate this file with mockery.
var _ skip.First = &MoqFirstMixed{}

// MoqFirstMixed is a mock implementation of skip.First.
//
//	func TestSomethingThatUsesFirst(t *testing.T) {
//
//		// make and configure a mocked skip.First
//		mockedFirst := &MoqFirstMixed{
//			PingFunc: func() string {
//				panic("mock out the Ping method")
//			},
//		}
//
//		// use mockedFirst in code that requires skip.First
//		// and then make assertions.
//
//	}
type MoqFirstMixed struct {
	// PingFunc mocks the Ping method.
	PingFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Ping holds details about calls to the Ping method.
		Ping []struct {
		}
	}
	lockPing sync.RWMutex
}

// Ping calls PingFunc.
func (mock *MoqFirstMixed) Ping() string {
	callInfo := struct {
	}{}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	if mock.PingFunc == nil {
		var (
			s string
		)
		return s
	}
	return mock.PingFunc()
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedFirst.PingCalls())
func (mock *MoqFirstMixed) PingCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// ResetPingCalls reset all the calls that were made to Ping.
func (mock *MoqFirstMixed) ResetPingCalls() {
	mock.lockPing.Lock()
	mock.calls.Ping = nil
	mock.lockPing.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqFirstMixed) ResetCalls() {
	mock.lockPing.Lock()
	mock.calls.Ping = nil
	mock.lockPing.Unlock()
}

// MoqSecondMixed is a mock implementation of skip.Second.
//
//	func TestSomethingThatUsesSecond(t *testing.T) {
//
//		// make and configure a mocked skip.Second
//		mockedSecond := &MoqSecondMixed{
//			PongFunc: func() string {
//				panic("mock out the Pong method")
//			},
//		}
//
//		// use mockedSecond in code that requires skip.Second
//		// and then make assertions.
//
//	}
type MoqSecondMixed struct {
	// PongFunc mocks the Pong method.
	PongFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Pong holds details about calls to the Pong method.
		Pong []struct {
		}
	}
	lockPong sync.RWMutex
}

// Pong calls PongFunc.
func (mock *MoqSecondMixed) Pong() string {
	callInfo := struct {
	}{}
	mock.lockPong.Lock()
	mock.calls.Pong = append(mock.calls.Pong, callInfo)
	mock.lockPong.Unlock()
	if mock.PongFunc == nil {
		var (
			s string
		)
		return s
	}
	return mock.PongFunc()
}

// PongCalls gets all the calls that were made to Pong.
// Check the length with:
//
//	len(mockedSecond.PongCalls())
func (mock *MoqSecondMixed) PongCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPong.RLock()
	calls = mock.calls.Pong
	mock.lockPong.RUnlock()
	return calls
}

// ResetPongCalls reset all the calls that were made to Pong.
func (mock *MoqSecondMixed) ResetPongCalls() {
	mock.lockPong.Lock()
	mock.calls.Pong = nil
	mock.lockPong.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *MoqSecondMixed) ResetCalls() {
	mock.lockPong.Lock()
	mock.calls.Pong = nil
	mock.lockPong.Unlock()
}
